services:
    app:
        container_name: app
        build:
            context: ./.docker/app
            dockerfile: Dockerfile
        restart: always
        command: php -S 0.0.0.0:8001 -t public
        volumes:
            - .:/var/www
        ports:
            - "8001:8001"
            - "9003:9003"
        networks:
            - app_network
        depends_on:
            - db
        environment:
            XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
            PHP_IDE_CONFIG: "serverName=app"

    db:
        container_name: db
        image: 'postgres:17-alpine'
        ports:
            - '5551:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-password}'
            POSTGRES_DB: '${DB_DATABASE:-app_db}'
            POSTGRES_USER: '${DB_USERNAME:-user}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-password}'
        volumes:
            - 'app_db:/var/lib/postgresql/data'
        networks:
            - app_network

volumes:
    app_db:
        driver: local

networks:
    app_network:
        driver: bridge
